### PR TITLE
den1k/transactable entity

### PR DESCRIPTION
**Pull request by den1k**
@huahaiy impl + tests for https://github.com/juji-io/datalevin/issues/48

### CODE REVIEW

**Comment by den1k** [comment]
@huahaiy does this PR work for you?

**Comment by huahaiy** [comment]
This looks great!. Would you mind updating the doc strings in the core namespace to reflect the changes? Thanks!

**Comment by den1k** [comment]
Thanks for merging @huahaiy! Still have an open todo to update docs I didn't get t this weekend.

**Comment by huahaiy** [comment]
@den1k  I will cut a release tomorrow. If you could get the docs in, it would be great!

**Comment by den1k** [comment]
Setting a reminder to do this today. Might only get there tomorrow

**Pull request merged**
